name: Deploy to Separate Live Repository

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'
      - 'docs/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      actions: write
    
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build static files
        run: |
          echo "🔨 Building static files..."
          SKIP_ENV_VALIDATION=true NODE_ENV=production npm run build
          echo "✅ Build completed"
          ls -la out/
      
      - name: Verify build output
        run: |
          echo "📁 Checking build output..."
          if [ ! -f "out/index.html" ]; then
            echo "❌ index.html not found in out directory"
            ls -la out/
            exit 1
          fi
          echo "✅ index.html found"
          echo "📊 Build output contents:"
          ls -la out/
      
      - name: Deploy to separate live repository
        run: |
          echo "🚀 Deploying to live repository..."
          
          # Clone the live repository
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/omeans-team/omeans-team-live.git live-repo
          cd live-repo
          
          # Switch to main branch
          git checkout main || git checkout -b main
          
          # Remove all existing files
          git rm -rf . || true
          
          # Copy static files from build output
          cp -r ../out/* .
          
          # Add .nojekyll file
          touch .nojekyll
          
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add all files
          git add .
          
          # Commit
          git commit -m "Deploy static files from main repository - $(date)" || echo "No changes to commit"
          
          # Push to live repository
          git push origin main --force
          
          echo "✅ Deployment completed"
      
      - name: Verify deployment
        run: |
          echo "🔍 Verifying deployment..."
          sleep 10
          curl -s -o /dev/null -w "%{http_code}" https://omeans-team.github.io/omeans-team-live/ || echo "Site not yet available"
      
      - name: Create deployment summary
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: commits } = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: context.payload.before,
              head: context.payload.after
            });
            
            const changedFiles = commits.files || [];
            const additions = changedFiles.reduce((sum, file) => sum + file.additions, 0);
            const deletions = changedFiles.reduce((sum, file) => sum + file.deletions, 0);
            
            const summary = `## 🚀 Live Repository Deployment Summary
            
            **Live Repository:** \`omeans-team/omeans-team-live\` (public)
            **Source Repository:** \`${context.repo.owner}/${context.repo.repo}\` (private)
            **Commit:** \`${context.payload.head_commit.id.substring(0, 7)}\`
            **Author:** ${context.payload.head_commit.author.name}
            **Date:** ${new Date(context.payload.head_commit.timestamp).toLocaleString()}
            
            ### 📊 Build Statistics
            - **Files Changed:** ${changedFiles.length} files
            - **Additions:** +${additions} lines
            - **Deletions:** -${deletions} lines
            - **Total Changes:** ${additions + deletions} lines
            
            ### 🔗 Links
            - **Live Site:** https://omeans-team.github.io/omeans-team-live/
            - **Source Code:** https://github.com/${context.repo.owner}/${context.repo.repo} (private)
            - **Live Repository:** https://github.com/omeans-team/omeans-team-live
            
            ### 📝 Changes Made
            \`\`\`
            ${context.payload.head_commit.message}
            \`\`\`
            
            ---
            *This deployment was automatically generated from the private main repository.*`;
            
            try {
              const issue = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: '🚀 Live Repository Deployed: ' + context.payload.head_commit.message.split('\n')[0],
                body: summary,
                labels: ['deployment', 'live-repository', 'auto-generated']
              });
              
              console.log('✅ Deployment summary issue created: #' + issue.data.number);
            } catch (error) {
              console.error('❌ Failed to create deployment summary:', error.message);
            }
